"""create votes table

Revision ID: 16dffe4011c8
Revises: 8ee735182fef
Create Date: 2022-11-15 11:43:30.019963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dffe4011c8'
down_revision = '8ee735182fef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # op.drop_table('sqlite_sequence')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    op.drop_table('votes')
    # ### end Alembic commands ###
